<?php

// $Id: os_custom.module 887 2009-09-24 15:51:14Z jhedstrom $

/**
 * @file
 * OpenSourcery base customizations.
 */

/**
 * Trigger our custom contexts
 */
function os_custom_init() {
  // don't fire any contexts on the front page
  if (drupal_is_front_page()) {
    return;
  }

  global $user;
  $context = 'os_custom_not_team_page';

  // are we viewing a team page?
  $node = menu_get_object();
  if (arg(0) == 'node' && arg(2) == NULL && $node && $node->type == 'team') {
    $context = 'os_custom_team_page';
  }

  foreach ($user->roles as $rid => $rname) {
    //context_set_by_condition($context, $rid);
  }
}

/**
 * Implementation of hook_context_conditions().
 */
function os_custom_context_conditions() {
  $items = array();
  $items['os_custom_team_page'] = array(
    '#title' => t('Roles (team page)'),
    '#description'=> t('Set this context for any of the given roles--only if we are viewing a team page.'),
    '#type' => 'checkboxes',
    '#options' => user_roles(),
  );
  $items['os_custom_not_team_page'] = array(
    '#title' => t('Roles (not team page)'),
    '#description'=> t('Set this context for any of the given roles--only if we are NOT viewing a team page.'),
    '#type' => 'checkboxes',
    '#options' => user_roles(),
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 *
 * - Sets the revisions as enabled for new content types.
 */
function os_custom_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'node_type_form':
      if (!isset($form['#node_type']->orig_type)) {
        $options = array();
        // Set to published by default.
        $options[] = 'status';
        // Enable revisions by default.
        $options[] = 'revision';
        $form['workflow']['node_options']['#default_value'] = $options;
      }
      break;

    case 'team_node_form':
      break;
  }
}

/**
 * Implementation of hook_imagecache_default_presets().
 */
function os_custom_imagecache_default_presets() {
  module_load_include('imagecache.inc', 'os_custom');
  return _os_custom_imagecache_default_presets();
}

/**
 * Preprocess page variables.
 */
function os_custom_preprocess_page(&$vars) {
  if (isset($vars['footer_message'])) {
    // Replace @year with current year.
    $vars['footer_message'] = str_replace('@year', format_date('Y'), $vars['footer_message']);
  }
}

