<?php
// $Id$
/**
 * @file
 * Social networking features for Donor Rally.
 */

  /**
   * Implementation of hook_link_alter().
   */
function donor_rally_social_link_alter(&$links, $node) {
  static $css_added = FALSE;
  foreach (array('facebook', 'forward', 'twitter') as $service) {
    if (isset($links['service_links_' . $service])) {
      if (!$css_added) {
        drupal_add_css(drupal_get_path('module', 'donor_rally_social') . '/donor-rally-social.css');
        $css_added = TRUE;
      }
      // Set additional classes.
      $links['service_links_' . $service]['attributes']['class'] = 'donor-rally-social-links donor-rally-social-links-' . $service;

      // @TODO Alter pre-populated message.
    }
  }
}